import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "@/components/navbar";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="flex gap-2">
          <Link href="/">Home</Link>
          <Link href="/profile">Profile</Link>
          <a href="/">home</a>
          <a href="/profile">profile</a>
        </div> */}
        <Toaster position="bottom-right" />
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="flex gap-2">
//           <Link href="/">Home</Link> <Link href="/profile">Profile</Link>
//           <a href="/">home</a> <a href="/profile">profile</a>
//         </div>
//         {children}
//       </body>
//     </html>
//   );
// }
